# Generated by Django 4.2.30 on 2026-04-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='Слово')),
                ('translation', models.CharField(max_length=100, verbose_name='Перевод')),
                ('example', models.TextField(blank=True,
                                             verbose_name='Пример использования')),
                ('created_at', models.DateTimeField(auto_now_add=True,
                                                    verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
            },
        ),
    ]
